#
# Copyright (c) 2025, 2026 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Nightly"

on:
  schedule:
    - cron: '0 10 * * 0-6'

env:
  MVN_VERSION: 3.9.9
  MVN_ARGS: |
    -B -fae -e -ntp
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
    -Dmaven.wagon.http.retryHandler.count=3
    -Dcache.enabled=true

jobs:
  resolve:
    runs-on: ubuntu-22.04
    outputs:
      extensions: ${{ steps.resolve.outputs.extensions }}
      versions: ${{ steps.resolve.outputs.versions }}
    steps:
      - uses: actions/checkout@v6
      - id: resolve
        shell: bash
        run: |
          etc/scripts/resolve.sh >> "${GITHUB_OUTPUT}"
  prime-build:
    needs: resolve
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ${{ fromJSON(needs.resolve.outputs.versions) }}
    name: prime-build/${{ matrix.version }}
    steps:
      - uses: actions/checkout@v6
      - name: Helidon priming build
        uses: ./.github/actions/common
        with:
          free-space: true
          build-cache: read-write
          build-cache-id: ${{ matrix.version }}
          maven-cache: read-write
          setup-latest-java: true
          run: |
            etc/scripts/prime-build.sh --version ${{ matrix.version }}
  build:
    needs: [ resolve, prime-build ]
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        extension: ${{ fromJSON(needs.resolve.outputs.extensions) }}
    name: ${{ matrix.extension.id }}/latest-java
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/common
        with:
          build-cache: read-only
          build-cache-id: ${{ matrix.extension.helidon_version }}
          maven-cache: read-only
          setup-latest-java: true
          test-artifact-name: ${{ matrix.extension.id }}-latest-java
          free-space: true
          run: |
            mvn --version
            mvn ${MVN_ARGS} \
              -f extensions/${{ matrix.extension.id }}/pom.xml \
              -Dorg.slf4j.simpleLogger.showThreadName=true \
              -Dsurefire.reportNameSuffix=latest-java \
              -Ptests \
              verify
